[package]
name = "my-executable"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-library = { path = "../my-library" }
smol = "1.0"
